//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public int Id_Steam { get; set; }
        public int Id_Epic { get; set; }
        public int Id_Ubisoft { get; set; }
        public string ImagePatch { get; set; }
    
        public virtual Epic Epic { get; set; }
        public virtual Steam Steam { get; set; }
        public virtual Ubisoft Ubisoft { get; set; }
    }
}
